name: Deploy Streamlit App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-east-1  # Replace with your AWS region

      # Build and push Docker image to ECR
      - name: Build and push Docker image to ECR
        run: |
          docker build -t ${{ secrets.ECR_REPOSITORY_URI }} .
          docker tag ${{ secrets.ECR_REPOSITORY_URI }} ${{ secrets.ECR_REPOSITORY_URI }}
          docker push ${{ secrets.ECR_REPOSITORY_URI }}

      # Deploy to ECS
      - name: Deploy to ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ./task_definition.json
          service: nyc-streamlit-service
          cluster: nyc-streamlit-app
          wait-for-service-stability: true

      # (Optional) Debug ECS Service and Tasks
      - name: Debug ECS Service
        run: |
          aws ecs describe-services --cluster nyc-streamlit-app --services nyc-streamlit-service

      - name: Debug ECS Tasks
        run: |
          aws ecs list-tasks --cluster nyc-streamlit-app

      # Verify Deployment
      - name: Verify Deployment
        run: |
          APP_URL="http://streamlit-alb-1076202224.us-east-1.elb.amazonaws.com:8501" # Update this with your ALB DNS name
          sleep 30  # Wait for 30 seconds to allow the app to initialize
          if curl --silent --fail "$APP_URL"; then
            echo "Streamlit App is live at $APP_URL"
          else
            echo "Deployment failed or the app is not reachable."
            exit 1
          fi
