name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest .

    # Step 4: Push the Docker Image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

    # Step 5: SSH into EC2 and Deploy
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v0.1.12
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ec2-user
        key: ${{ secrets.EC2_PRIVATE_KEY }}
        script: |
          # Stop any running container
          docker stop streamlit-app || true
          docker rm streamlit-app || true

          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

          # Run the container
          docker run -d -p 8501:8501 --name streamlit-app ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest
