name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the Repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Step 3: Build the Docker Image
      - name: Build Docker Image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest .

      # Step 4: Push the Docker Image to Docker Hub
      - name: Push Docker Image to Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

      # Step 5: Set up SSH Key for EC2 Access
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-add ~/.ssh/id_rsa

      # Step 6: Deploy to EC2
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: nyc-docker-test  # Change to your instance's SSH username (e.g., ec2-user, ubuntu, etc.)
          key: ${{ secrets.EC2_SSH_KEY }}
          port: 22  # Adjust if you're using a different SSH port
          script: |
            # Stop any running container
            docker stop streamlit-app || true
            docker rm streamlit-app || true

            # Pull the latest Docker image
            docker pull ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

            # Run the container
            docker run -d -p 8501:8501 --name streamlit-app ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest
