name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest .

    # Step 4: Push Docker Image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

    # Step 5: SSH into EC2 and Deploy
    - name: Deploy to EC2
      uses: appleboy/ssh-action@v1.2.0
      with:
        host: ${{ secrets.EC2_PUBLIC_IP }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        port: 22
        timeout: 1800  # Timeout set to 30 minutes (adjustable)
        script_stop: true
        script: |
          set -e

          # Stop and remove any existing container in one step
          docker stop streamlit-app || true
          docker rm streamlit-app || true

          # Pull the image only if it's not available locally
          echo "Pulling the latest Docker image"
          docker pull ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

          # Clean up unused images to free up space
          echo "Removing unused Docker images"
          docker image prune -f

          # Run the Docker container
          echo "Running the Docker container"
          docker run -d -p 8501:8501 --name streamlit-app ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest
