name: Deploy Streamlit App to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up AWS credentials (ensure you have set these secrets in your GitHub repository)
      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Log in to Amazon ECR
      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          region: us-east-1  # Replace with your AWS region

      # Pull the Docker image from ECR
      - name: Pull Docker image from ECR
        run: |
          docker pull ${{ secrets.ECR_REPOSITORY_URI }}

      # Deploy to AWS ECS
      - name: Deploy to AWS ECS
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ./task_definition.json
          service: nyc-streamlit-service
          cluster: nyc-streamlit-app
          wait-for-service-stability: true

      # (Optional) Verify Deployment
      - name: Verify Deployment
        run: |
          APP_URL="54.88.171.149:8501"
          if curl --silent --fail "$APP_URL"; then
            echo "Streamlit App is live at $APP_URL"
          else
            echo "Deployment failed or the app is not reachable."
            exit 1
          fi
