name: CI/CD for Streamlit App

on:
  push:
    branches:
      - main

jobs:
  Build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout the Repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build the Docker Image
    - name: Build Docker Image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest .

    # Step 4: Push the Docker Image to Docker Hub
    - name: Push Docker Image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest

    # Step 5: Add SSH Key for EC2
    - name: Add SSH Key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/ec2_key.pem
        chmod 600 ~/.ssh/ec2_key.pem

    # Step 6: Deploy Docker Image on EC2
    - name: Deploy to EC2
      run: |
        ssh -i ~/.ssh/ec2_key.pem ubuntu@${{ secrets.EC2_PUBLIC_IP }} << 'EOF'
          set -e
          
          # Stop and remove any existing container
          docker stop streamlit-app || true
          docker rm streamlit-app || true
          
          # Pull the latest Docker image
          docker pull ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest
          
          # Clean up old images
          docker image prune -f
          
          # Run the Docker container
          docker run -d -p 8501:8501 --name streamlit-app ${{ secrets.DOCKER_USERNAME }}/streamlit-app:latest
        EOF
