name: Build and Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main  # Trigger deploy on code push to the main branch
  pull_request:
    branches:
      - main  # Trigger deploy on PR to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (version 3.x)
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Log in to Azure using Service Principal credentials
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Step 5: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: myacrstreamlit.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 6: Build and Push Docker Image to Azure Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t myacrstreamlit.azurecr.io/mystreamlit-app:latest .
          docker push myacrstreamlit.azurecr.io/mystreamlit-app:latest

      # Step 7: Deploy to Azure Web App (Production Slot Only)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: mystreamlit-app
          images: myacrstreamlit.azurecr.io/mystreamlit-app:latest

      # Optional Step: Debugging (only runs if there is a failure)
      - name: Debug Environment
        if: failure()
        run: |
          echo "Node.js version:"
          node --version || echo "Node.js not installed"
          echo "npm version:"
          npm --version || echo "npm not installed"
          ls -al /home/runner/work/_actions/azure/webapps-deploy/v2/
