name: Build and Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main  # Trigger deploy on code push to the main branch
  pull_request:
    branches:
      - main  # Trigger deploy on PR to the main branch
  workflow_dispatch:  # Allow manual trigger of the workflow

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Python environment (version 3.x)
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Step 3: Install dependencies from requirements.txt
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from the requirements file

      # Step 4: Log in to Azure using Service Principal credentials
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}  # Ensure your Service Principal credentials are stored in secrets

      # Step 5: Log in to Azure Container Registry (ACR)
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: myacrstreamlit.azurecr.io  # ACR login server
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Step 6: Build and Push Docker Image to Azure Container Registry
      - name: Build and Push Docker Image
        run: |
          docker build -t myacrstreamlit.azurecr.io/mystreamlit-app:latest .  # Build Docker image
          docker push myacrstreamlit.azurecr.io/mystreamlit-app:latest  # Push image to ACR

      # Step 7: Deploy to Azure Web App (Production Slot)
      - name: Deploy to Azure Web App - Production
        uses: azure/webapps-deploy@v2
        with:
          app-name: mystreamlit-app  # Azure Web App name
          images: myacrstreamlit.azurecr.io/mystreamlit-app:latest  # Image from ACR

      # Optional: Deploy to Staging Slot (if staging exists)
      - name: Deploy to Azure Web App - Staging (Optional)
        if: success() && github.ref == 'refs/heads/main'  # Trigger only on successful main branch push
        uses: azure/webapps-deploy@v2
        with:
          app-name: mystreamlit-app  # Azure Web App name
          slot-name: staging  # Target staging slot
          images: myacrstreamlit.azurecr.io/mystreamlit-app:latest  # Image from ACR

      # Step 8: Swap Staging to Production (Optional)
      - name: Swap Staging to Production
        if: success() && github.ref == 'refs/heads/main'
        uses: azure/webapps-deploy@v2
        with:
          app-name: mystreamlit-app  # Azure Web App name
          source-slot: staging
          target-slot: production

      # Step 9: Verify the deployment
      - name: Verify Deployment
        run: |
          for i in {1..5}; do
            echo "Attempt $i to verify the deployment..."
            curl --fail https://mystreamlit-app.azurewebsites.net && break || sleep 30
          done

      # Optional Step: Debug step (only runs if there is a failure)
      - name: Debug Environment
        if: failure()  # Run only if a failure occurs
        run: |
          echo "Node.js version:"
          node --version || echo "Node.js not installed"
          echo "npm version:"
          npm --version || echo "npm not installed"
          ls -al /home/runner/work/_actions/azure/webapps-deploy/v2/  # List action folder
