name: Build and Deploy Streamlit App to Azure

on:
  push:
    branches:
      - main  # Trigger deploy when code is pushed to the main branch
  pull_request:
    branches:
      - main  # Trigger deploy on PR to the main branch

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python environment
      - name: Set up Python 3.x
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Install dependencies from requirements.txt

      # Log in to Azure
      - name: Log in to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          client-secret: ${{ secrets.AZURE_CLIENT_SECRET }}

      # Log in to Azure Container Registry
      - name: Log in to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          login-server: myacrstreamlit.azurecr.io
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build and push Docker image
      - name: Build and Push Docker Image
        run: |
          docker build -t myacrstreamlit.azurecr.io/streamlit-taxi-fare-app:latest .
          docker push myacrstreamlit.azurecr.io/streamlit-taxi-fare-app:latest

      # Deploy to Azure Web App (Production Slot)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v1
        with:
          app-name: streamlit-taxi-fare-app  # Azure App Service name
          images: myacrstreamlit.azurecr.io/streamlit-taxi-fare-app:latest
          slot-name: production  # Default slot for deployment

      # Optional: Set AZURE_STORAGE_CONNECTION_STRING environment variable for the app
      - name: Set AZURE_STORAGE_CONNECTION_STRING for Streamlit App
        run: |
          echo "AZURE_STORAGE_CONNECTION_STRING=${{ secrets.AZURE_STORAGE_CONNECTION_STRING }}" >> $GITHUB_ENV

      # Verify Deployment
      - name: Verify Deployment
        run: |
          curl --fail https://streamlit-taxi-fare-app.azurewebsites.net || exit 1  # Check if the app is up and running

      # Optional: Swap Slots if using Staging Slot
      - name: Swap Staging to Production
        if: success() && github.ref == 'refs/heads/main'
        run: |
          az webapp deployment slot swap \
            --name streamlit-taxi-fare-app \
            --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
            --slot staging \
            --target-slot production
